apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pub-sub-perf-tool.fullname" . }}-flow
  labels:
    {{- include "pub-sub-perf-tool.labels" . | nindent 4 }}
data:
  flow.yaml: |
    {{- .Values.flowConfig | nindent 4 }}
